---
# site.yml - Hauptplaybook für Multi-Rollen-Konfiguration
# Führt verschiedene Rollen zur Systemkonfiguration und -härtung aus

- name: Apply configurations to all servers
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Führe Vorbereitungs-Tasks aus
      ansible.builtin.import_tasks: pre_tasks.yml
      tags: always

  roles:
    # Systemfacts erfassen (Hostname, IP, OS, CPU, RAM, Dateisysteme, Pakete)
    - { role: audit, tags: ['audit', 'always'] }
    
    # OS- und Sicherheitsupdates durchführen
    - { role: update, tags: ['update', 'setup'] }
    
    # Grundlegende Systemkonfiguration
    - { role: base, tags: ['base', 'setup'] }
    
    # Webserver-Konfiguration (Nginx oder Apache)
    - { role: web_service, tags: ['web', 'services'] }
    
    # Docker Host Setup
    - { role: docker_host, tags: ['docker', 'services'] }
    
    # Sicherheitsprüfungen
    - { role: security_checks, tags: ['security', 'audit'] }
    
    # Systemhärtung nach CIS-Benchmarks
    - { role: hardening, tags: ['harden', 'security'] }
    
    # Sicherheitstools (fail2ban, PortSentry, psad)
    - { role: security_tools, tags: ['security', 'tools'] }
    
  post_tasks:
    - name: Prüfe ob ein Neustart erforderlich ist
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
      tags: always
      
    - name: Zeige Neustart-Warnung an
      ansible.builtin.debug:
        msg: "HINWEIS: Server '{{ ansible_hostname }}' benötigt einen Neustart!"
      when: ansible_os_family == "Debian" and reboot_required.stat.exists | default(false)
      tags: always 